_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 53
            "3":
                - 13
                - 16
                - 55
            "4": 3.12.2
            "5": 0.20.1
            "6": 4.36.0
            "12": 0.20.1
            "13": darwin-arm64
act_function:
    value: relu
d_model:
    value: 2048
depth_transformer_encoder_blocks:
    value: 4
dropout_rate_1:
    value: 0.2
dropout_rate_2:
    value: 0.2
lr_scratch:
    value: 0.00015831212555496548
n_attention_heads:
    value: 4
transition_weight:
    value: -2.4153843697466884
