_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 53
            "3":
                - 13
                - 16
                - 55
            "4": 3.12.2
            "5": 0.20.1
            "6": 4.36.0
            "12": 0.20.1
            "13": darwin-arm64
act_function:
    value: gelu
depth_transformer_encoder_blocks:
    value: 8
dropout_rate_1:
    value: 0.1
dropout_rate_2:
    value: 0.3
lr_esm2:
    value: 3.0160413175427764e-06
lr_scratch:
    value: 5.954564981261678e-05
n_attention_heads:
    value: 2
transition_weight:
    value: -3.944201843464827
weight_class_scaler:
    value: 0
