name: Code linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"
          auto-activate-base: true

#      - name: Cache pip packages
#        uses: actions/cache@v4
#        with:
#          path: ~/.cache/pip
#          key: ${{ runner.os }}-pip-ruff
#          restore-keys: |
#            ${{ runner.os }}-pip-

#      - name: Install dependencies
#        run: |
#          pip install ruff

#      - name: ruff check
#        run: |
#          ruff check predict.py 

#      - run: echo "Linting workflow ran"
